import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
 
// Font files can be colocated inside of `pages`
const mainFont = localFont({ src: './fonts/ocr-a.ttf' })
const secondaryFont = localFont({ src: './fonts/ocr-b.ttf' })
export const metadata: Metadata = {
  title: "Tape Shift",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} ${secondaryFont.className}`}>
        {children}
      </body>
    </html>
  );
}
